name: 自动同步源仓库KHwang9883/MobileModels
on:
  repository_dispatch:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: xxz13352/MobileModels
          ref: master  # 这里从 main 改为 master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 配置Git用户
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: 关联并拉取源仓库最新代码
        run: |
          git remote add upstream https://github.com/KHwang9883/MobileModels.git
          git fetch upstream
          git checkout master  # 这里从 main 改为 master
          git merge upstream/master --no-edit --allow-unrelated-histories  # 这里从 main 改为 master

      - name: 推送到自己的Fork仓库
        run: |
          git push origin master  # 这里从 main 改为 master
